//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int Itemsid { get; set; }
        public string ItemsName { get; set; }
        public string CategoryName { get; set; }
        public string ItemsText { get; set; }
        public Nullable<System.DateTime> ItemsDate { get; set; }
        public string ItemsLink { get; set; }
    }
}
